# Public tasks
[tasks.default]
clear = true
dependencies = [
    "clean",
    "check",
    "test",
    "build",
]

[tasks.check]
description = "Check code integrity"
clear = true

[tasks.test]
description = "Check code integrity"
clear = true

[tasks.build]
description = "Build nachos"
clear = true

[tasks.clean]
description = "Clean up workspace"
clear = true
