extend = [ { path = "Makefile.private.toml" }, { path = "Makefile.env.toml" }]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
clear = true
dependencies = [
    "clean",
    "check",
    "test",
    "build",
]

[tasks.check]
description = "Check code integrity"

[tasks.test]
description = "Run all tests"

[tasks.build]
description = "Build nachos and dependencies"

[tasks.clean]
description = "Clean up workspace"

[tasks.run-client]
workspace = false
dependencies = [
    { name = "run", path = "nachos-client/Makefile.toml" }
]

[tasks.run-backend]
workspace = false
dependencies = [
    { name = "build", path = "libguac-sys" },
    { name = "run", path = "nachos/Makefile.toml" }
]

[tasks.serve]
description = "Run nachos"
workspace = false
dependencies = [
    { name = "build", path = "libguac-sys" }
]
run_task = { name = ["serve-backend", "serve-client"], fork = true, parallel = true }
