[env]
GUACAMOLE_VERSION = "1.4.0"
LDFLAGS = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "", mapping = { "macos" = "-L/opt/homebrew/lib/" } }
CFLAGS_BASE = "-Wno-newline-eof -Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-undef-prefix -Wno-incompatible-function-pointer-types"
CFLAGS = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "${CFLAGS_BASE}", mapping = { "macos" = "-I/opt/homebrew/include ${CFLAGS_BASE}" } }
