[package]
name = "libguac-sys"
version = "0.1.0"
edition = "2021"
links = "guac"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies.bindgen]
version = "0.59"
