extend = "../Makefile.env.toml"

# Public tasks
[tasks.check]
description = "Check libguac-sys source integrity"
dependencies = ["build-guacamole-server"]

[tasks.build]
description = "Build libguac-sys"
dependencies = ["build-guacamole-server"]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
description = "Running tests for libguac-sys"
dependencies = ["build-guacamole-server"]

[tasks.clean]
description = "Clean up libguac-sys workspace"
dependencies = ["clean-dist"]


# Private task
[tasks.build-guacamole-server]
description = "Build guacamole-server"
private = true
dependencies = ["git-submodule-sync"]
condition_script = [
    "[[ -d \"dist\" ]] && exit 1 || exit 0"
]
script = """
    cd guacamole-server
    autoreconf -fi
    ./configure \
        --disable-guacd \
        --disable-kubernetes \
        --disable-guaclog \
        --disable-guacenc \
        --with-freerdp-plugin-dir="$PWD/../dist/freerdp-plugins" \
        --prefix="$PWD/../dist"
    make
    make install
    git clean -fxd
"""

[tasks.clean-dist]
description = "Clean up libguac-sys shared resources"
private = true
command = "rm"
args = ["-rf", "dist"]

[tasks.git-submodule-sync]
description = "Update guacamole-server source from remote"
private = true
condition_script = [
    "[[ -d \"dist\" ]] && exit 1 || exit 0"
]
script = """
git submodule foreach --recursive git stash clear
git submodule foreach --recursive git stash
git submodule update --remote --init
git submodule foreach --recursive git checkout ${GUACAMOLE_VERSION}
git submodule foreach --recursive git reset --hard
git submodule foreach --recursive git stash pop || exit 0
"""
