[package]
name = "nachos-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.wasm-bindgen]
version = "0.2"

[dependencies.yew]
version = "0.19"

[dependencies.yew-router]
version = "0.16"
